export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const SELECT_FONT = 'SELECT_FONT';
export const CHANGE_PREVIEW_TEXT = 'CHANGE_PREVIEW_TEXT';
